---
  - name: Install Hadoop resource-manager (jobtracker)
    yum: name=hadoop-yarn-resourcemanager state=present
    when: ansible_os_family == "RedHat"
  
  - name: Start zookeeper service
    service: name=hadoop-yarn-resourcemanager enabled=yes state=started
    when: ansible_os_family == "RedHat"